name: dev-frontend-main-deploy

on:
  push:
    branches: [ dev ]
    paths: 'frontend/main/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./frontend/main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.1.jh1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: main
  deploy:
    needs: tag
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      # Deploy
      - name: Deploy dev to Vercel
        uses: amondnet/vercel-action@v19
        id: vercel-action-staging
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_MAIN_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_MAIN_PROJECT_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          working-directory: ./frontend/main
