name: main-frontend-main-deploy

on:
  push:
    branches: [ main ]
    paths: 'frontend/main/**'
  workflow_dispatch:

jobs:
  deploy:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      # Deploy
      - name: Deploy ${GITHUB_REF##*/} to Vercel
        uses: amondnet/vercel-action@v19
        id: vercel-action-staging
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_MAIN_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_MAIN_PROJECT_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          working-directory: ./frontend/main
